### ISSUE TITLE
Missing Requests Import Statement in RESTful c2

### ISSUE THREAD

**Issue by Mr-8lobby** [its-a-feature/Apfell#17]
The import statement from the server config:
https://github.com/its-a-feature/Apfell/blob/c4ddee87ae44c05a46c0fbb4a7891a190ec295bf/C2_Profiles/RESTful_Patchthrough/server#L10
Needs to be added to the Dockerfile:
https://github.com/its-a-feature/Apfell/blob/master/C2_Profiles/RESTful_Patchthrough/Dockerfile
`RUN pip install requests`

**Comment by its-a-feature** [comment]
Good catch! 

In the next update (end of next week) that whole profile is disappearing in favor of a new profile that gives way more flexibility for configuration of HTTP traffic.

**Comment by its-a-feature** [comment]
The RESTfulPatchthrough profile has been removed in favor of the HTTP profile with more configuration options.
