### ISSUE TITLE
Upload command does not work.

### ISSUE THREAD

**Issue by clhefton** [its-a-feature/Apfell#18]
Upload either doesn't work, or the documentation is unclear. I downloaded a file from an agent called "exfilme". Here's the output:

```
(Fri Mar 06 2020 11:34:50)
{
  "agent_file_id": "392a3013-93ae-4a8a-9798-8d2e3d4fbf0a",
  "chunks_received": 0,
  "cmd": "download",
  "complete": false,
  "deleted": false,
  "id": 54,
  "operation": "default",
  "operator": "apfell_admin",
  "path": "/Apfell/app/files/default/downloads/bobsmachine/exfilme",
  "task": 227,
  "timestamp": "03/06/2020 19:34:50",
  "total_chunks": 1
}
(Fri Mar 06 2020 11:34:50)
Finished download
```

Still nothing works for uploading. I've tried everything I can think of.
```
upload {"remote_path": "/home/bob/exfilme", "file_id": 54}
	- failed to get file info from the database: 'file'
upload {"remote_path": "/home/bob/exfilme", "file_id": "54"}
	- failed to get file info from the database: 'file'
upload {"remote_path": "/home/bob/exfilme", "file_id": 54, "file": "exfilme"}
	- failed to get file info from the database: 'file'
upload {"remote_path": "/home/bob/exfilme", "file": "exfilme"}
	- failed to get file info from the database
upload {"remote_path": "/home/bob/exfilme", "file_id": "392a3013-93ae-4a8a-9798-8d2e3d4fbf0a"}
	- failed to get file info from the database: 'file'
upload {"remote_path": "/home/bob/exfilme", "file": "/Apfell/app/files/default/downloads/bobsmachine/exfilme"}
	- failed to get file info from the database:
```

I can reference the ID in the URL but not with the upload command. I.e., this works: https://54.184.42.114/api/v1.3/files/download/392a3013-93ae-4a8a-9798-8d2e3d4fbf0a

Also despite that it can be referenced by ID as per the URL listed under Hosted Files, it does not show under hosted files.

Trying to add it manually to the Hosted Files again using the local path "/Apfell/app/files/default/downloads/bobsmachine/exfilme" fails silently.

Trying to add it with the UUID it gave fails with "failed to find that file in your operation". 

Please update documentation to be more clear, and advise how to reference downloaded files. 

EDIT: I am using the viper payload on a linux machine.
I can't find a version file, but my Apfell instance was installed on Jan 22, 2020

**Comment by its-a-feature** [comment]
Which branch are you using? There's a massive update coming out today that should fix this:

<img width="1567" alt="Screen Shot 2020-03-06 at 12 35 52 PM" src="https://user-images.githubusercontent.com/5313261/76120870-416c1180-5fa7-11ea-8489-e24cf0f338a9.png">

In general though, you should be able to type `upload`, hit enter, a popup box will come up, select the file you want to upload, give it the remote path, and it _should_ all be good for you. The above screenshot is for the version that's dropping today. The first command was selecting a file through the popup (hence why there's the modified params button), but the second two are using that file id to keep writing that file to other places if desired.

The latest documentation for the update coming out today is at: https://docs.apfell.net/v/version1.4/

**Comment by its-a-feature** [comment]
The new version is out. Can you try with the new version and see if you have the same issue?
