### ISSUE TITLE
Atlas implant not working

### ISSUE THREAD

**Issue by mike0240** [its-a-feature/Apfell#22]
Might be a bug?

Description:
Atlas payload executes and continues running in the background, but does not callback to server. I've used procmon to check and there doesn't seem to be any network traffic generated by it.

Steps to reproduce:
1. Start C2 default server
2. Generate Atlas implant, changing callback_host to server's ip address
3. Download implant and execute on Windows 10 vm

Expected:
The implant shows up in Active Callbacks list

Apfell Server:
Running on: Kali 2020.1 x86_64

Windows 10 VM:
OS: Windows 10 Pro
Version: 10.0.18363

**Comment by its-a-feature** [comment]
Can you check a few things for me:
1. What IP/Port/SSL combination are you using for the web UI
2. In the default server, when you look at files, there's a `config.json` file with a field called `apfellBase` at the bottom. Does this match up with what you have in step 1?
3. When you go to "Payload Management", there's a "config" button next to your payload. Can you show me what your configuration options are?
4. When was the last time you updated Apfell?

**Comment by airzero24** [comment]
I should of put this in the README but Atlas doesn't allow self-signed certificates. I'll be creating this as a compile option in the future.

If you would like to use a sefl-signed cert, you can add the following line to before the loop for `CheckIn()` in `Program.cs`.

```
using System.Net;
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
```

**Comment by mike0240** [comment]
1. I'm using 192.168.100.11, port 80 and no SSL.
2. apfellBase is: http://192.168.100.11:9000/api/v1.4/agent_message
3. 
![atlas_config_img](https://user-images.githubusercontent.com/62734086/79109687-670ce780-7dab-11ea-933a-88835620a03a.JPG)
4. Apfell was updated 1-2 weeks ago

**Comment by Ne0nd0g** [comment]
I couldn't get it to work either. I ran SharpHound and it didn't do anything.....

**Comment by airzero24** [comment]
@mike0240 there was an update to Atlas 7 days ago that may resolve this issue. Could you also verify that the default C2 profile container is running as your pointing Atlas towards the default 9000 port for the container.

**Comment by its-a-feature** [comment]
@mike0240 Ah, I think I see your issue. Your `apfellBase` shouldn't have the port 9000 on it. That is telling the `default` docker container where to forward the request to (which would just be `http://192.168.100.11/api/v1.4/agent_message`.

**Comment by mike0240** [comment]
Yeah, it's working now. Thanks!
