### ISSUE TITLE
pull access denied for c2_profile_base

### ISSUE THREAD

**Issue by Kofl** [its-a-feature/Apfell#24]
Hi,

I did an fresh installation on Ubuntu18 and during ./start_apfell.sh I get the error:

Step 1/3 : From c2_profile_base, repository does not exist or may require docker login
same for websocket:latest and payload_type_base

Afterwards, only apfell, postgres and rabbitmq containers are runnning. C2 and payload are missing.

Any hints?

Thanks,
Thomas

**Comment by Kofl** [comment]
and ...

Apfell/Payload_Types/Dockerfile: no such file or directory

**Comment by its-a-feature** [comment]
Good catch! I fixed the branch and re-pushed. Please pull from master again and try starting apfell

**Comment by Kofl** [comment]
Awesome, thanks for the fast repsonse, works like a charm again.  Thx for that great tool.
