### ISSUE TITLE
Feature request SOCKS proxy for 1.5

### ISSUE THREAD

**Issue by atropineal** [its-a-feature/Apfell#25]
It's already listed as a feature for 1.5, but I would like to vote for it explicitly! :)

Currently for Apfell JXA agents we SSH out from the compromised client device to a server we control in order to establish a reverse SOCKS pivot, but in-C2 SOCKS would be a very welcome addition since it does not introduce new egress indicators (apart from frequency/volume, obviously), and has a certainty of egress that SSH does not.

Also, is there any known approximate ETD for Apfell 1.5?

Thank you for your excellent work on Apfell!

**Comment by its-a-feature** [comment]
Hey! It's being worked into the back-end currently; however, not every agent will support it. I really wish I could do it from the JXA agent specifically, but I haven't been able to get threading working with JXA in general :/ 

There's a lot of big developmental updates, UI changes, and developer quality-of-life features that are going into. I'm hoping it'll be ready within a month or two 🤞
