### ISSUE TITLE
HTTP C2 Profile NoMatch keeps hitting ignoring message

### ISSUE THREAD

**Issue by AltAccountCuzblueTeamWatchesGithub** [its-a-feature/Apfell#26]
I have tried several different VM's and get them all working using Default C2 profile and JXA-agent fine. I've used Ubuntu 18.04 and latest Kali to test out.

When using the sample HTTP C2 profile sample config.json (i updated the IP's where relevant) and the sample Agent config i cannot get a fully functional callback. i get initial callback with info (seems like the HTTP POST is fine) and then it never checks in again, and i can't issue commands. error from Sanic is: Failed to get a value: /<test:string>, 'Request' object has no attribute 'raw_args'

I've tried with and without encryption.

It seems like it can't seem to find the "message" value, and keeps hitting a NoMatch condition. the GET request with message in q parameter just hist nomatch. 

I've tried putting the "message" all over, in body of POST, in cookie, in other GET param to no avail. Just really struggling that last few days to get a working HTTP C2 profile going. On a whim im wondering if any recent changed to the guts have caused any weirdness with HTTP C2 profile? does it still work for the world + dog and im just dumb? thanks.

**Comment by AltAccountCuzblueTeamWatchesGithub** [comment]
Here's a quick video showing what's what if it helps https://www.dropbox.com/s/yyh5rhn73brznbl/Help.mp4?dl=0

**Comment by its-a-feature** [comment]
Oh good catch! The versions must have crept passed me since the last main push. I'll add in a version to the pip install for that container.
