### ISSUE TITLE
Apfell immediately shuts down

### ISSUE THREAD

**Issue by clhefton** [its-a-feature/Apfell#27]
The `apfell_apfell` container immediately shuts down after starting and won't start again even manually. It always hangs on `./wait-for-postgres`. I am running on Ubuntu 18.04.

docker log apfell_postgres
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  database system was shut down at 2020-06-11 17:48:13 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  incomplete startup packet
LOG:  incomplete startup packet
LOG:  incomplete startup packet
```

docker logs apfell_apfell
```
wait-for-postgres.sh: waiting 5 seconds for 127.0.0.1:5432
wait-for-postgres.sh: 127.0.0.1:5432 is available after 0 seconds
[Errno 2] No such file or directory
wait-for-postgres.sh: waiting 5 seconds for 127.0.0.1:5432
wait-for-postgres.sh: 127.0.0.1:5432 is available after 0 seconds
[Errno 2] No such file or directory
```

apfell-docker/wait-for-postgres.sh -h 127.0.0.1 -p 5432
```
wait-for-postgres.sh: waiting 5 seconds for 127.0.0.1:5432
wait-for-postgres.sh: 127.0.0.1:5432 is available after 0 seconds
```

I don't even know where to start debugging this, but commenting out the `command` line in docker_compose makes it crash on `python3` instead of the wait-for script, and taking just the `wait-for` part out of the command makes it crash at `"python /Apfell/serv…"`

I'm not very familiar with docker but I also tried changing 
```
["./wait-for-postgres.sh", "127.0.0.1:5432", "--", "python", "/Apfell/server.py"]
```
to 
```
["./wait-for-postgres.sh", "127.0.0.1:5432", "--", "python", "./server.py"]
```
and got the same result. Changing to `["/Apfell/wait-for-postgres.sh", "127.0.0.1:5432", "--", "python", "/Apfell/server.py"]` gives the error that /Apfell/wait-for-postgres.sh can't be found.

**Comment by its-a-feature** [comment]
Ok, one of the common issues is that there's a postgres instance already running on the box that's preventing apfell's postgres from binding to the port.

If you run `sudo ./status_check.sh` what's the output?

**Comment by its-a-feature** [comment]
Is this your first time starting apfell, or has it been running for a while and you're now encountering this issue?

**Comment by clhefton** [comment]
I used it a few months back. I'm using the newest version. I found some new info. I did a reset --hard HEAD and removed all the docker containers then restarted with default configs. 

I don't know how, but it has to do with changing any of the db parameters. I was trying to change the default apfell DB password and it does the same thing every time I try. When I ran with a fresh install and no changes, it doesn't work anymore

**Comment by its-a-feature** [comment]
hm... ok, try the following:
sudo ./status_check.sh
    do this to make sure that the containers are actually gone
sudo ./reset_postgres_database.sh
    do this to remove any saved database information
sudo ./reset_rabbitmq_data.sh
    do this to reset rabbitmq data
sudo ./setup_apfell.sh
    this will go through to re-parse the default database information from __init__.py and re-create the Docker file for postgres
sudo ./start_apfell.sh

**Comment by clhefton** [comment]
Ok I did all that and it did the same thing. I didn't notice those scripts, so that is useful. I'll play around with settings for awhile until I narrow down the culprit.

**Comment by its-a-feature** [comment]
Oh, if it works with a fresh install, then i can almost guarantee that there's an issue with modifying the database password. I bet there's some places where the updated password/username isn't being pulled in

**Comment by clhefton** [comment]
Ok I figured it out. It actually has nothing to do with the db. It's the cert paths. I'm very confused why they wouldn't work. At first I thought it was because I was giving an absolute system path but I copied them to the apfell-docker/app/ssl/ folder and used a relative path and it still didn't work. 

I ran `stop_apfell`, ran all `reset-*` scripts above, did `git reset`, copied files to app/ssl again, and ran `setup` again before starting apfell and had the same result.

Key files: 
```
ssl_cert_path = './app/ssl/fullchain.pem'  
ssl_key_path = './app/ssl/privkey.key'  
```

Any ideas what I'm missing? I'm using letsencrypt certs. I've tried fullchain.pem and cert.pem both

**Comment by its-a-feature** [comment]
running setup again will blow away your cert files (https://github.com/its-a-feature/Apfell/blob/master/setup_apfell.sh#L39), so make sure to copy them back over afterwards. 
are you setting `use_ssl` to True (https://github.com/its-a-feature/Apfell/blob/master/apfell-docker/app/__init__.py#L19)?

You should be able to stop apfell, copy those files over, start apfell, and be good to go with use_ssl to true. Can you try that and look at the output from `sudo ./display_output.sh apfell_apfell`? The fact that you're getting `[Errno 2] No such file or directory` makes me think that there's a mismatch between the filenames specified in the ssl_cert_path and the actual files on disk in that `./app/ssl` folder

**Comment by clhefton** [comment]
yes, I am. Here's the full config: 
```
server_ip = '172.25.126.12'  # this will be used by the browser to callback here
listen_port = '443'
listen_ip = '0.0.0.0'  # IP to bind to for the server, 0.0.0.0 means all local IPv4 addresses
ssl_cert_path = './app/ssl/fullchain.pem'
ssl_key_path = './app/ssl/privkey.key'
whitelisted_ip_blocks = ['0.0.0.0/0']  # only allow connections from these IPs to the /login and /register pages
use_ssl = True
server_header = "nginx 1.17.0"
log_size = 1024000  # grows indefinitely (0), or specify a max size in Bytes (1MB). If 0, will not rotate!
keep_logs = True  # set to false for speed improvement, but no logs will be kept
# --------------------------------------------
# --------------------------------------------
# --------------------------------------------
db_name = 'apfell_db'
db_user = 'apfell_user'
db_pass = '#######'
max_log_count = 1
```
The pathnames are copy-pasted, so there's no misspelling. 

Do implants use the same certs as the server? If not, I can just specify different ones for the implants and it won't matter.

**Comment by its-a-feature** [comment]
hm... the certs don't get stamped into the agents, the part you're configuring right now is just for your browser access to the UI. If you want to configure the SSL certs that agents would see when connecting in, you'd modify the certs associated with the different c2 profile docker containers.

When agents connect in, they connect _through_ the C2 profile docker containers which then reach back and forward the requests to the main server. For example, for the default profile you'd be dropping those cert files here (https://github.com/its-a-feature/Apfell/tree/master/C2_Profiles/default) and modifying these lines to have the names of those files (https://github.com/its-a-feature/Apfell/blob/master/C2_Profiles/default/config.json#L28-L29)

**Comment by its-a-feature** [comment]
This entire process is one of the things being updated for the next update because it's not that intuitive

**Comment by clhefton** [comment]
Thanks Cody! I just reverted to using the Apfell ones, I don't know why the others weren't working. I assumed the implants used the same certs for HTTPS connections. I'll try changing the defaults for the implants, the Apfell server itself doesn't have to use custom certs. Thanks for the help!

**Comment by clhefton** [comment]
Knowing me, it was probably a careless mistake somewhere along the way. You can close this issue
