### ISSUE TITLE
HTTP C2 profile with JXA: failed connection

### ISSUE THREAD

**Issue by clhefton** [its-a-feature/Apfell#28]
Does the jxa payload require https? I'm testing on a private network, with `http://<private-ip>` as the only URL in `urls[]`, so I don't have HTTPS since letsencrypt requires a public domain and self-signed certs don't work with the apfell-jxa. 

However, I get this error every time I run a payload:

```
error in post_agent_message: HTTPSConnectionPool(host='localhost', port=XXXX): 
Max retries exceeded with url: /api/v1.4/agent_message (Caused by 
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5589ef8a58>: 
Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by its-a-feature** [comment]
ah, this is auto-updated in the next push, but for now make sure that your apfellBase in the HTTP's config. apfellBase tells the c2 docker container where to redirect the connections to (it should point to the same address that you use to browse via the web UI). So, if you're browsing the webUI at https://[ip here]:8443, then apfellBase should be `https://localhost:8443`. 

The JXA payload requires http OR non-self signed certs (that's a requirement of apple security i haven't found a way around without requiring a full .app application)

**Comment by clhefton** [comment]
Ah, actually it was a pebcak error....I'd had it listening on <private IP> rather than 0.0.0.0 in config, but the `apfellBase` was set to `localhost` instead of <privateIP>. Got it working. Thank you!

**Comment by its-a-feature** [comment]
oh lol that'll do it! Glad you figured it out :)
