### ISSUE TITLE
[Improvement] Create Homebrew package

### ISSUE THREAD

**Issue by t94j0** [its-a-feature/Apfell#3]
This project is awesome!

It would be great if there were a Homebrew package for this project so that one could run `brew install apfell` to install it.

I can work on this tomorrow if you think it would be a good feature.

**Comment by its-a-feature** [comment]
Thanks! I've never actually put anything through that process before - what all is required to update things after it's been pushed that way?

**Comment by t94j0** [comment]
It's actually very easy to write Python [Homebrew formulas](https://github.com/Homebrew/brew/blob/master/docs/Python-for-Formula-Authors.md).

Normally, it's easiest to write the formula when a [setup.py](https://github.com/kennethreitz/setup.py) is made for the project. It's basically just a more 'pythonic' version of your `setup.sh` file, and is very platform-independent.

Once it's pushed, for each release, the Homebrew formula needs to be updated, which should be changing the version number in the Homebrew formula.

I've got a non-working setup.py file in my fork that I can merge when I'm done.

**Comment by t94j0** [comment]
Sorry for taking so long, but it's been a busy week.
Just got the brew formula created.

It can be installed by running:
1. `brew tap t94j0/security`
2. `brew install --HEAD apfell`

The `--HEAD` is required since a release hasn't been created yet. When one is created, you can make an issue and assign it to me.

I'm having trouble right now getting the service to work, but once the formula is installed, you will be able to run `brew services start apfell` and the web server will start.
