### ISSUE TITLE
Poseidon Payload Cannot Change Sleep Interval - Unmarshal error

### ISSUE THREAD

**Issue by tophertimzen** [its-a-feature/Apfell#33]
In Apfell v1.4 while using the Poseidon payload, I am unable to run the command `sleep` to change the interval of check-in. 

Running `sleep 5` results in the following with Poseidon in Apfell v1.4 

```
json: cannot unmarshal number into Go value of type Main.args
```

Installation was done by following [https://docs.apfell.net/installation](https://docs.apfell.net/installation).

**Comment by tophertimzen** [comment]
FWIW; the help page for the command listing says that `sleep [time in seconds]` but the code at https://github.com/its-a-feature/Apfell/blob/master/apfell-docker/app/payloads/poseidon/payload/poseidon.go#L299 shows that sleep is expecting 2 arguments. Trying to run that also errors, this time with error `invalid character '1' after top-level value` if the command ran is `sleep 5 10`

**Comment by tophertimzen** [comment]
Apparently if you write `sleep` and then hit `enter`, it brings up a menu to configure the task. The correct arguments to sleep thus are `sleep {"jitter": #, "sleep": #}`

This was not at all intuitive as I would expect to be able to write `sleep 5 5`. Furthermore, we refer to the time of sleep as `sleep` and not as `interval` which is not aligned to what other C2 platforms call it, which made this more confusing.

**Comment by its-a-feature** [comment]
I'm sorry that was confusing. In general for Apfell, if the command takes parameters and you don't supply any, then you can type the command and hit enter to get a popup dialog to fill in the required parameters. 

The next version of Apfell is coming out this week and has that addressed within Poseidon (along with a bunch of other things).

**Comment by tophertimzen** [comment]
Awesome, thanks @its-a-feature! Looking forward to the new version.
