### ISSUE TITLE
Another macOS error

### ISSUE THREAD

**Issue by Soutcast** [its-a-feature/Apfell#5]
I am able to sign in to Apfell and register new users however the default payloads aren't loading and visiting the page just says that the "socket is closed".
This also applies to the operations page as the default operation isn't loading either and trying to add a new operation also says that the "socket is closed".
Other pages display similar errors.

Any ideas?

**Comment by Soutcast** [comment]
Resolved by visiting the site on address 127.0.0.1

Note: when visiting the site through 'localhost' or '0.0.0.0' it yields these page display errors.

Is there an explanation to these strange behaviour?

**Comment by its-a-feature** [comment]
in `__init__.py`, what did you set your `server_ip` to? The IP/domain you set there is the IP/domain you need to connect to. I believe the issue you're running into is that your `server_ip` value is set to `127.0.0.1` and you tried browsing in your web client to `localhost`. 

If you change that value to `localhost` and browse to `localhost` then it'll all work as well. If you have an actual domain name for your server, then you put that there and browse to the domain name as well. I believe the reason it fails otherwise is that your browser is connected to one 'domain' (i.e. localhost) and the websockets are trying to connect to another 'domain' (i.e. 127.0.0.1), which causes web issues.

The `0.0.0.0` address is the address that the server is 'bound' to. `0.0.0.0` is essentially an alias for all IPV4 addresses on your system, so you wouldn't/can't actually browse to that address.

**Comment by Soutcast** [comment]
Ah ok, the reason that I set the `server_ip` to `127.0.0.1` is because i ran into some other issues having it set as `localhost`.
My question is if I leave the `server_ip` as `127.0.0.1` will everything work as expected?

**Comment by its-a-feature** [comment]
oh really? what issue did you run into with it as `localhost`? as long as what you browse to and what's listed there are the same, it should work.

**Comment by Soutcast** [comment]
Changed the `server_ip` back to `localhost` and everything seems to be working now.
I have provided some macOS debug info below which helped me when I had issues during installation

Apfell Debug Info:
- uninstall postgres "brew uninstall --ignore-dependencies postgres"
- remove postgres folder "rm -r /usr/local/var/postgres"
- kill processes on port 80 "netstat -vanp tcp | grep 80", "kill PID"

**Comment by Soutcast** [comment]
Another error popped up after trying to import a `.json` payload.

`[2019-03-26 20:13:15 +1100] [94806] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/peewee_async.py", line 170, in get
    return list(result)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/Desktop/test/Apfell_Extension/Apfell/app/api/payloadtype_api.py", line 495, in import_payload_type_func
    payload_type = await db_objects.get(query, ptype=ptype['ptype'])
  File "/usr/local/lib/python3.7/site-packages/peewee_async.py", line 172, in get
    raise model.DoesNotExist
app.database_models.model.PayloadTypeDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 556, in handle_request
    response = await response
  File "/usr/local/lib/python3.7/site-packages/sanic_jwt/decorators.py", line 215, in decorated_function
    return await response
  File "/usr/local/lib/python3.7/site-packages/sanic_jwt/decorators.py", line 114, in decorated_function
    return await _do_protection(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sanic_jwt/decorators.py", line 90, in _do_protection
    response = await response
  File "/Users/username/Desktop/test/Apfell_Extension/Apfell/app/api/payloadtype_api.py", line 468, in import_payloadtype_and_commands
    error_list.append(await import_payload_type_func(ptype, operator, operation))
  File "/Users/username/Desktop/test/Apfell_Extension/Apfell/app/api/payloadtype_api.py", line 503, in import_payload_type_func
    external=ptype['external'])
KeyError: 'external'`

**Comment by its-a-feature** [comment]
what json payload are you trying to install?

**Comment by its-a-feature** [comment]
I just recently updated the backend (which is why the version is now 1.2) to include a new key for payload types - 'external'. I just added a patch to set that value in case it isn't supplied in the payload type json file.

**Comment by Soutcast** [comment]
Thanks that seems to have fixed the issue.

**Comment by Soutcast** [comment]
New error after I start my c2 profile. When i try to browse to a page after it is started I either receive `Not found` or `Page not found`

Console output after c2 profile is started:

`Exception ignored in: <function _releaseLock at 0x1066dd400>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
    _lock.release()
RuntimeError: cannot release un-acquired lock
Ignoring exception from logging atfork <_StderrHandler <stderr> (WARNING)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stdout> (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stdout> (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stderr> (NOTSET)> release method: cannot release un-acquired lock'

**Comment by its-a-feature** [comment]
what c2 profile?

**Comment by Soutcast** [comment]
I imported the chrome-extension profile made by xorrior

**Comment by its-a-feature** [comment]
ah, you'll need to reach out to him about that one then

**Comment by Soutcast** [comment]
Ok will do

**Comment by Soutcast** [comment]
The same issue occurs when trying to start the RESTful Patchthrough c2profile

**Comment by Soutcast** [comment]
Just double checking that this isn't an issue with Apfell. This may be a silly comment but,
this is the error I receive after I start the chrome-extension c2profile and then try to browse to the operations management page:

![error](https://user-images.githubusercontent.com/42455146/55153939-c8194b80-51a7-11e9-8711-d1cd9e16be09.png)

Are you sure that this is just an error with the c2profile?

**Comment by its-a-feature** [comment]
What if you start the `RESTful Patchthrough` profile? Do you get the same issue?

**Comment by Soutcast** [comment]
The `RESTful Patchthrough` module displays the same error in the terminal output but doesn't have the behaviour of not finding pages.

Exception ignored in: <function _releaseLock at 0x104a19400>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
    _lock.release()
RuntimeError: cannot release un-acquired lock
Ignoring exception from logging atfork <_StderrHandler <stderr> (WARNING)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stderr> (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stdout> (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stdout> (NOTSET)> release method: cannot release un-acquired lock

**Comment by Soutcast** [comment]
This is what it looks like after I start the profile before I try to navigate to other pages:

![after profile starts](https://user-images.githubusercontent.com/42455146/55155716-33fdb300-51ac-11e9-89fd-3554cec36c4a.png)

**Comment by Soutcast** [comment]
Just experimented by changing the `server_ip` in `_init_.py` to `127.0.0.1` instead of `localhost` and that seems to have fixed this `page not found` error. Very strange.

**Comment by its-a-feature** [comment]
hm... that's very odd indeed. What if you try using an actual IP of the computer? I wonder if there's some weirdness going on with the loopback address that's messing something up? I'm always accessing the Apfell server from a browser on another computer, so I never actually end up using the `127.0.0.1` or `localhost` server ip values

**Comment by Soutcast** [comment]
If you set the `server_ip` to the IP address of the computer, everything is fine and no errors show. Seems to be the same as when you set the `server_ip` to `127.0.0.1`

**Comment by its-a-feature** [comment]
When you set the `server_ip` to the address of the computer, do you still get those errors when starting the `RESTful Patchthrough` c2 profile? If so, can you provide more logging output? You should be able to click the "status" button for that profile after you start it to keep getting output - I'm curious if the profile code is throwing an error somewhere, if it's the main Apfell server throwing errors, or both. I haven't been able to reproduce though. Can you give some status on your system too? You're on high sierra with python3.7 installed via brew right?

**Comment by Soutcast** [comment]
System Status:
macOS version: High Sierra
Python version: 3.7.2
Apfell installation: Installed via GitHub repo through `setup.sh` script

Terminal output after starting `RESTful Patchthrough` with `server_ip` set to ip address of computer:

Exception ignored in: <function _releaseLock at 0x10740e400>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 226, in _releaseLock
    _lock.release()
RuntimeError: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stdout> (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stdout> (NOTSET)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <_StderrHandler <stderr> (WARNING)> release method: cannot release un-acquired lock
Ignoring exception from logging atfork <StreamHandler <stderr> (NOTSET)> release method: cannot release un-acquired lock
[2019-03-29 11:07:24 +1100] - (sanic.access)[INFO][1:9]: GET http://192.168.0.18/api/v1.2/c2profiles/RESTful%20Patchthrough/start  200 297

User interface after starting `RESTful Patchthrough` with `server_ip` set to ip address of computer:

![UI after RESTful start](https://user-images.githubusercontent.com/42455146/55200639-2596b200-5213-11e9-85c0-477b5f3c0d4d.png)

Terminal output after clicking "status" button for `RESTful Patchthrough`:

[2019-03-29 11:10:35 +1100] - (sanic.access)[INFO][1:9]: GET http://192.168.0.18/api/v1.2/c2profiles/RESTful%20Patchthrough/status  200 32

User interface after clicking "status" button for `RESTful Patchthrough`:

![UI after status RESTful](https://user-images.githubusercontent.com/42455146/55200732-9dfd7300-5213-11e9-9819-765791c73cd4.png)

**Comment by its-a-feature** [comment]
I've tracked the issue down to this line https://github.com/its-a-feature/Apfell/blob/master/app/api/c2profiles_api.py#L338 specifically when Apfell is installed on a macOS device. There's something about the way python3 is installed via brew that is causing a change  I don't see on Ubuntu. 

For reference, I just took a fresh Ubuntu 18.04 VM, installed Apfell the same way you did, and didn't get any of the weird warnings about locks. I'll continue to dig into this, but in the meantime, if you can run this on Ubuntu, it should work.

**Comment by Soutcast** [comment]
Any updates on how this issue is progressing?

**Comment by its-a-feature** [comment]
I'm still working on why that's happening in python3.7, but despite it happening, the RESTful c2 profile starts and works as expected. 

In some recent testing, I've also noticed Safari being weird (it sends the request to start the service every time you load the page), so try doing it in Google Chrome.
