### ISSUE TITLE
Unable to get callback from remote system

### ISSUE THREAD

**Issue by kwiha** [its-a-feature/Apfell#9]
managed to set it up and execute the payloads on the remote system however I'm unable to get the call back. How does one setup the listener? I've generated payloads using the default everything ie port 80 but nothing. I'm able to curl the payload from the remote host however when i execute the the payload on the remote system, there's no callback. I think I might be missing the setting up the listener phase. 
<img width="1580" alt="Screen Shot 2019-08-09 at 8 42 06 PM" src="https://user-images.githubusercontent.com/7115967/62805132-0116e480-bae7-11e9-8373-00f3b18d6433.png">
<img width="768" alt="Screen Shot 2019-08-09 at 8 42 41 PM" src="https://user-images.githubusercontent.com/7115967/62805134-0116e480-bae7-11e9-8590-cfe08230996b.png">
<img width="1313" alt="Screen Shot 2019-08-09 at 8 43 17 PM" src="https://user-images.githubusercontent.com/7115967/62805136-0116e480-bae7-11e9-9b55-c301ed6f994c.png">

**Comment by its-a-feature** [comment]
Hey! I think I see the issue. For your callback host, it should be _either_ `http://192.168.61.147` or `https://192.168.61.147`. The description of the `http(s)` is just to help indicate that it can be either or.

**Comment by kwiha** [comment]
It worked :-) Thanks for your quick response.
